title: Anthony Do
logo: "/assets/img/profile2.jpeg"
description: 

  <p></p>

  Aspiring data scientist & mathematician knowledgeable in statistical analysis and programming visualizations to utilize the power of data.

  <br><br>

  <a href="/assets/pdf/AnthonyDo_Resume.pdf" class="button">Resume</a> 

  <br><br>
  <div class="center">
    <a href="https://www.linkedin.com/in/dosanity/" class="button">View My LinkedIn Profile</a> 
  </div>
google_analytics:
theme: jekyll-theme-minimal

