---
title: Anthony Do
logo: /assets/img/profile2.jpeg
description: Aspiring data scientist & mathematician knowledgeable in statistical analysis and programming visualizations to utilize the power of data.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
---